[General]
autoConnect=1
ResetTertminal=1

[OpenDialog]
HW=C:\Users\kk\Desktop\Current\hw\speed\
CAN=C:\Users\kk\Documents\Embarcadero\Studio\Projects\launcher_terminal\Doc\temp\
WIFI=C:\Users\kk\Desktop\Current\wifi_s\
SERVER=C:\Users\kk\Documents\Embarcadero\Studio\Projects\launcher_terminal\Doc\Server\
all=C:\Users\kk\Documents\Embarcadero\Studio\Projects\launcher_terminal\Doc\_TEMPLATES\LM_GWC\
[SaveDialog]
HW=C:\Users\kk\Desktop\Current\hw\test\
CAN=C:\Users\kk\Documents\Embarcadero\Studio\Projects\launcher_terminal\Doc\temp\
WIFI=C:\Users\kk\Desktop\Current\wifi_s\
SERVER=
all=
[main]
comport=-1
[db]
host=192.168.20.9
port=6033
name=tvz_main
login=tvz-conf-user
dll=C:\Program Files (x86)\MySQL\Connector ODBC 8.0\myodbc8w.dll
password=N3FzQTRRRWd6b1pRZ2VyUU53VTQ=
[TempCard]
TemCardCheck=1
TempCardEdit=1
TempCardBlank=0000000000CA9A3B0E00100E8403C158

#0000000000CA9A3B0E00100E8403C158
#C7353A4200CA9A3B0E00100E84034C8B
