object fr_Terminal: Tfr_Terminal
  Left = 0
  Top = 0
  Caption = 'Terminal'
  ClientHeight = 450
  ClientWidth = 775
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  TextHeight = 15
  object mmTerminal: TMemo
    Left = 0
    Top = 41
    Width = 775
    Height = 409
    Align = alClient
    DoubleBuffered = True
    ParentDoubleBuffered = False
    ScrollBars = ssBoth
    TabOrder = 0
    ExplicitWidth = 641
    ExplicitHeight = 386
  end
  object plButtons: TPanel
    Left = 0
    Top = 0
    Width = 775
    Height = 41
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 1
    ExplicitWidth = 641
    object Panel1: TPanel
      Left = 0
      Top = 0
      Width = 775
      Height = 40
      Align = alTop
      TabOrder = 0
      object btnExit: TButton
        AlignWithMargins = True
        Left = 696
        Top = 4
        Width = 75
        Height = 32
        Align = alRight
        Caption = 'Exit'
        TabOrder = 0
        OnClick = btnExitClick
        ExplicitLeft = 705
        ExplicitTop = 1
        ExplicitHeight = 38
      end
      object btnGetName: TButton
        AlignWithMargins = True
        Left = 328
        Top = 4
        Width = 75
        Height = 32
        Align = alLeft
        Anchors = []
        Caption = 'GetName'
        Enabled = False
        TabOrder = 1
        OnClick = btnGetNameClick
        ExplicitLeft = 110
        ExplicitTop = 14
        ExplicitHeight = 25
      end
      object btnInfo: TButton
        AlignWithMargins = True
        Left = 85
        Top = 4
        Width = 75
        Height = 32
        Align = alLeft
        Anchors = []
        Caption = 'INFO'
        Enabled = False
        TabOrder = 2
        OnClick = btnInfoClick
        ExplicitLeft = 61
        ExplicitTop = 3
      end
      object btnPing: TButton
        AlignWithMargins = True
        Left = 4
        Top = 4
        Width = 75
        Height = 32
        Align = alLeft
        Anchors = []
        Caption = 'Ping'
        Enabled = False
        TabOrder = 3
        OnClick = btnPingClick
        ExplicitLeft = 8
        ExplicitTop = 10
        ExplicitHeight = 25
      end
      object btnRead: TButton
        AlignWithMargins = True
        Left = 166
        Top = 4
        Width = 75
        Height = 32
        Align = alLeft
        Anchors = []
        Caption = 'Read'
        Enabled = False
        TabOrder = 4
        OnClick = btnReadClick
        ExplicitLeft = 89
        ExplicitTop = 9
        ExplicitHeight = 25
      end
      object btnWrite: TButton
        AlignWithMargins = True
        Left = 247
        Top = 4
        Width = 75
        Height = 32
        Align = alLeft
        Anchors = []
        Caption = 'Write'
        Enabled = False
        TabOrder = 5
        ExplicitLeft = 220
        ExplicitTop = 3
      end
      object Button1: TButton
        AlignWithMargins = True
        Left = 409
        Top = 4
        Width = 75
        Height = 32
        Align = alLeft
        Anchors = []
        Caption = 'Print'
        TabOrder = 6
        OnClick = Button1Click
        ExplicitLeft = 110
        ExplicitTop = 16
        ExplicitHeight = 25
      end
      object Button4: TButton
        AlignWithMargins = True
        Left = 490
        Top = 4
        Width = 75
        Height = 32
        Align = alLeft
        Anchors = []
        Caption = 'Clear'
        TabOrder = 7
        OnClick = Button4Click
        ExplicitLeft = 519
        ExplicitTop = 3
      end
    end
  end
end
